config/routes.rb
Rails.application.routes.draw do
  root to: 'tickets#index'
  resources :events

  resources :tickets

end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
	validates :name, :seat_id_seq, :address, :price_paid, :email_address, :phone , presence: true ,length: {minimum: 3}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:artist, :description, :price_low, :price_high, :event_date)
    end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
 
  def index
    @tickets=Ticket.all
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
    @ticket=Ticket.find(params[:id])
  end

  # GET /tickets/new
  def new
    @ticket=Ticket.new
  end

  # GET /tickets/1/edit
  def edit
     @ticket=Ticket.find(params[:id])
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)
    if @ticket.save
    redirect_to action: :show, :id => @ticket.id
    else 
    render 'new'
    end  
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    @ticket = Ticket.find(params[:id])
 
    if @ticket.update(ticket_params)
    redirect_to tickets_path(@ticket.id)  
    else
    render 'edit'
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket=Ticket.find(params[:id])
      @ticket.destroy
      redirect_to :action => 'index'
  end

  private
    
    def ticket_params
      params.require(:ticket).permit(:name, :seat_id_seq, :address, :price_paid, :email_address, :phone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :artist %><br>
    <%= f.text_field :artist %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :prices_from%><br>
    <%= f.text_field :price_low %>
  </div>
  <div class="field">
    <%= f.label :To %><br>
    <%= f.text_field :price_high %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :event_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <thead>
    <tr>
      <th>Artist</th>
      <th>Description</th>
      <th>Price low</th>
      <th>Price high</th>
      <th>Event date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.artist %></td>
        <td><%= event.description %></td>
        <td><%= event.price_low %></td>
        <td><%= event.price_high %></td>
        <td><%= event.event_date %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Artist:</strong>
  <%= @event.artist %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Price low:</strong>
  <%= @event.price_low %>
</p>

<p>
  <strong>Price high:</strong>
  <%= @event.price_high %>
</p>

<p>
  <strong>Event date:</strong>
  <%= @event.event_date %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tickets</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tickets/_form.html.erb
  
  <% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>
      <ul>
      <% @ticket.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table border=0.5 >
    <tr><td>
    <%= f.label :name %><br></td>
   <td> <%= f.text_field :name %></td></tr>
   <tr><td>
    <%= f.label :seat %><br></td>
   <td> <%= f.text_field :seat_id_seq %></td>
  </tr>
  <tr><td>
    <%= f.label :address %><br></td>
  <td>  <%= f.text_area :address %></td>
  </tr>
  <tr><td>
    <%= f.label :price_paid %><br></td>
   <td> <%= f.text_field :price_paid %></td>
  </tr>
  <tr><td>
    <%= f.label :email_address %><br></td>
  <td>  <%= f.text_field :email_address %></td>
  </tr>
  <tr><td>
    <%= f.label :phone %><br></td>
  <td>  <%= f.text_field :phone %></td>
  </tr>
  <tr><td>
  <h2> <%= f.submit :SUBMIT %> </h2></td></tr>

  

app/views/tickets/edit.html.erb
<center><h1><u>Editing Tickets</u></h1>
<%= form_for @ticket , url: ticket_path(@ticket.id) ,method: :patch do |f| %>
<%= render :partial =>'form' , locals: {:f => f} %>
<% end %>

<%= link_to 'Show', ticket_path(@ticket.id) %> |
<%= link_to 'Back', tickets_path %>
</center>

app/views/tickets/index.html.erb
<h1>Listing tickets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Seat #</th>
      <th>Address</th>
      <th>Price paid</th>
      <th>Email address</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.name %></td>
        <td><%= ticket.seat_id_seq %></td>
        <td><%= ticket.address %></td>
        <td><%= ticket.price_paid %></td>
        <td><%= ticket.email_address %></td>
         <td><%= ticket.phone %></td>
        <td><%= link_to 'Show', ticket_path(ticket.id) %></td>
        <td><%= link_to 'Edit', edit_ticket_path(ticket.id) %></td>
        <td><%= link_to 'Destroy', ticket_path(ticket.id), method: :delete, data: { confirm: 'Are you sure want to delete the ticket?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket', new_ticket_path %>

app/views/tickets/new.html.erb
<center><h1><u>New Tickets</u></h1>
<%= form_for @ticket , url: tickets_path do |f| %>
<%= render :partial =>'form' , locals: {:f => f} %>


</center>
<% end %>
 

app/views/tickets/show.html.erb
<p> <h1>Ticket was successfully created </h1></p>

<p>
  <strong>Name:</strong>
  <%= @ticket.name %>
</p>

<p>
  <strong>Seat #:</strong>
  <%= @ticket.seat_id_seq %>
</p>

<p>
  <strong>Address:</strong>
  <%= @ticket.address %>
</p>

<p>
  <strong>Price paid:</strong>
  <%= @ticket.price_paid %>
</p>

<p>
  <strong>Email address:</strong>
  <%= @ticket.email_address %>
</p>
<p>
  <strong>Phone:</strong>
  <%= @ticket.phone %>
</p>
<p>
<%= link_to 'Edit', edit_ticket_path(@ticket.id) %> |
<%= link_to 'Back', tickets_path %>
</p>